spring:
 autoconfigure:
   exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
            org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, 
            org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
 cloud:
   gateway:
     routes:
       - id: web-forum-service
         uri: http://web-forum-service:9093
         predicates:
           - Path=/api/v1/web-forum-service/**
         filters:
           - StripPrefix=3

       - id: master-service
         uri: http://master-service:9092
         predicates:
           - Path=/api/v1/master-service/**
         filters:
           - StripPrefix=3

       - id: auth-service
         uri: http://auth-service:9094
         predicates:
           - Path=/api/v1/auth-service/**
         filters:
           - StripPrefix=3

 application:
   name: API-GATEWAY


