spring:
 autoconfigure:
   exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
 cloud:
   gateway:
     routes:
       - id: web-forum-service
         uri: http://localhost:9093
         predicates:
           - Path=/api/v1/web-forum-service/**
         filters:
           - StripPrefix=3

       - id: master-service
         uri: http://localhost:9092
         predicates:
           - Path=/api/v1/master-service/**
         filters:
           - StripPrefix=3

       - id: auth-service
         uri: lb://AUTH-SERVICE
         predicates:
           - Path=/api/v1/auth-service/**
         filters:
           - StripPrefix=3

 application:
   name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


